### ISSUE TITLE
알고리즘 스터디 방식 토의

### ISSUE THREAD

**Issue by CoodingPenguin** [CAU-Escape/algorithm-study#3]
**어떤 문제를 풀 것인가?**
- 유형별로 뽑아서 대표 문제 풀이
- 카카오/삼성 코딩테스트 기출 문제 풀이

**어떤 식으로 진행할 것인가?**
- 참고 : https://github.com/DKU-STUDY/Algorithm

**Comment by CoodingPenguin** [comment]
https://github.com/tony9402/baekjoon

**Comment by sm-amoled** [comment]
일반적으로 현재 배우고 있는 특정한 알고리즘을 익히려면 해당 알고리즘 카테고리에 맞는 문제를 쭉 푸는게 좋겠지만, 스터디같은 목적이라면 유형 관계 없이 무작위 유형에 대한 문제를 받아볼 수 있는 모의고사나 기출 문제 같은걸 풀이하는게 좋을 것이라 보입니다! 그래야 더 넓게 문제를 바라볼 수 있을 것 같아용

**Comment by CoodingPenguin** [comment]
- https://github.com/WeareSoft/algorithm-study
- https://github.com/Mirim-Study/Algorithm

**Comment by CoodingPenguin** [comment]
@sm-amoled 그럼 카카오, 삼성 기출 문제부터 풀어볼까요? 카카오는 프로그래머스, 삼성 기출은 백준에 있습니다!

**Comment by CoodingPenguin** [comment]
공통 서적, 문제집이 필요할 때까지는 각자 목표를 새우고 그것을 푸는 것으로 변경
